### PR TITLE
Added flags for Create menu

### PR DESCRIPTION
**Pull request by jeromemaurey**
Added flags for ability to generate configuration files for Configuration, Client Configuration, Database Configuration.
Unity_u33cyclk5H

### CODE REVIEW

**Comment by konraddysput** [comment]
hi @jasoncdavis0 ,

Thanks for your changes. Could you please give me more details why would you like to initialize database object without Backtrace client?

thanks!

**Comment by jeromemaurey** [comment]
Hello,

This is mostly UX, following the flow from packages like HDRP.
Unity_NEj8Cpheii

Cheers,

J.

**Comment by sbahra** [comment]
Hi Jerome! Thanks for the patch! During UX testing, we found that exposing three different configurations as such tended to make it easier for users to shoot themselves in the foot. All the three items are already configurable through the existing window which couples things correctly, while still allowing advanced power users to decouple for more advanced use-cases.

@jeromemaurey Alright if we close this out or was there a specific need or problem that's unaddressed?

**Comment by jeromemaurey** [comment]
Closed it.

I still think the main config should be exposed to the Create menu. Let me know if you want me to submit a PR for that file only ;)

**Comment by sbahra** [comment]
Ok! Sorry, I missed this message. @konraddysput What do you think?

**Comment by konraddysput** [comment]
@sbahra - latest Unity plugin version expose Backtrace configuration under Create menu. I think we add this sugestion to our source code

**Pull request closed without merging**
