### PR TITLE
Added quality and max height properties for screenshots and log type filtering

### PR DESCRIPTION
**Pull request by oddgames-david**

### CODE REVIEW

**Comment by sbahra** [comment]
Thanks very much for this @oddgames-david! The team is reviewing.

**Comment by troy-lamerton** [comment]
Hi, there has been an release (3.4.0 in April) and it seems these improvements weren't included.

@konraddysput what's the latest status of the new options for error logs and screenshots?

**Comment by konraddysput** [comment]
hi @troy-lamerton 
we're in the middle of preparing the backtrace-unity@3.5.0 release that will have most of the changes from this branch in the newest release. We will keep you posted once we will have the testable version ready.

**Comment by konraddysput** [comment]
hi @oddgames-david,
wanted to let you know that we've merged release/3.5.0 branch with those changes to the master branch. Your suggestions are now available in the official backtrace-unity version!

Since those changes are merged, should we close this pull request? 
Please let me know what you think about it!

**Pull request closed without merging**
